// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBe-YloHR3IpRbMYMf-GzrtbmRifPKQrI',
    appId: '1:733385124300:web:173a7c70122c25e0c81569',
    messagingSenderId: '733385124300',
    projectId: 'wenia-test',
    authDomain: 'wenia-test.firebaseapp.com',
    storageBucket: 'wenia-test.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXZDpdH4c_uJ7B_bJ6f85Cl-hrMTQ2sJY',
    appId: '1:733385124300:android:ec2fdbeaade51b8dc81569',
    messagingSenderId: '733385124300',
    projectId: 'wenia-test',
    storageBucket: 'wenia-test.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6WleUoS1CV7m99Ixe6Cs-bmOg0YAnkEo',
    appId: '1:733385124300:ios:c142e8bb88cf5e32c81569',
    messagingSenderId: '733385124300',
    projectId: 'wenia-test',
    storageBucket: 'wenia-test.appspot.com',
    iosBundleId: 'com.example.weniaTest',
  );
}
